const data = {
  products: [
    {
      _id: "1",
      name: "Cougar Slim Shirt",
      category: "Shirt",
      image: "images/p1.jpg",
      price: 120,
      brand: "Cougar",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },

    {
      _id: "2",
      name: "Cougar Fit Shirt",
      category: "Shirt",
      image: "images/p2.jpg",
      price: 110,
      brand: "Cougar",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },

    {
      _id: "3",
      name: "Cougar Free shirt",
      category: "Shirt",
      image: "images/p3.jpg",
      price: 225,
      brand: "Cougar",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Cougar Slim Pant",
      category: "Pant",
      image: "images/p4.jpg",
      price: 95,
      brand: "Cougar",
      rating: 4.9,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Cougar Free Pant",
      category: "Pant",
      image: "images/p5.jpg",
      price: 115,
      brand: "Cougar",
      rating: 4.2,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Cougar Fit Pant",
      category: "Pant",
      image: "images/p6.jpg",
      price: 97,
      brand: "Cougar",
      rating: 4.7,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
export default data;